### ISSUE TITLE
Problem with data.py

### ISSUE THREAD

**Issue by faisal-zaman** [soribadiaby/Deep-Learning-liver-segmentation-project#1]
There seems to be an error with data.py when creating test data

**Comment by soribadiaby** [comment]
Can you show me the error ?

**Comment by faisal-zaman** [comment]
> Can you show me the error ?

This is the error I face while running on PyCharm:

Traceback (most recent call last):
  File "C:/Users/Faisal/Documents/Textbooks/Masters/Master Thesis/Deep-Learning-liver-segmentation-project-master/data.py", line 103, in <module>
    create_test_data()
  File "C:/Users/Faisal/Documents/Deep-Learning-liver-segmentation-project-master/data.py", line 71, in create_test_data
    img=nibabel.load(os.path.join(test_data_path,image_name))
  File "C:\Users\Faisal\Documents\Deep-Learning-liver-segmentation-project-master\venv\lib\site-packages\nibabel\loadsave.py", line 53, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "raw/test\test"

Process finished with exit code 1

**Comment by soribadiaby** [comment]
Try to delete the "test" file located in the test folder and also the "train" file in the train folder

**Comment by faisal-zaman** [comment]
> Try to delete the "test" file located in the test folder and also the "train" file in the train folder

Thank you! It works now 😄
