### ISSUE TITLE
Issue after training data preprocessing

### ISSUE THREAD

**Issue by faisal-zaman** [soribadiaby/Deep-Learning-liver-segmentation-project#3]
I encounter an error after loading and preprocessing of the training data. When the test data is loaded this is the error I get: 

Traceback (most recent call last):
  File "C:/Users/Faisal/Documents/Textbooks/Masters/Master Thesis/Deep-Learning-liver-segmentation-project-master/train.py", line 171, in <module>
    train_and_predict()
  File "C:/Users/Faisal/Documents/Deep-Learning-liver-segmentation-project-master/train.py", line 131, in train_and_predict
    imgs_test, imgs_id_test = load_test_data()
  File "C:\Users\Faisal\Documents\Deep-Learning-liver-segmentation-project-master\data.py", line 98, in load_test_data
    imgs_id = np.load('imgs_id_test.npy')
  File "C:\Users\Faisal\Documents\Deep-Learning-liver-segmentation-project-master\venv\lib\site-packages\numpy\lib\npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'imgs_id_test.npy'

Process finished with exit code 1

**Comment by soribadiaby** [comment]
Try replacing (line 98) in data.py
```python
    imgs_id = np.load('imgs_id_test.npy')
    return [imgst, imgs_id]
```

by 
```python
    imgs_mask_test_true = np.load('imgsliv_test.npy')  #groundtruth masks
    return imgst, imgs_mask_test_true
```

in the notebook replace 

```python
imgs_test, imgs_id_test = load_test_data()
```

by
```python
imgs_test = load_test_data()[0]
```

**Comment by faisal-zaman** [comment]
> Try replacing (line 98) in data.py
> 
> ```python
>     imgs_id = np.load('imgs_id_test.npy')
>     return [imgst, imgs_id]
> ```
> 
> by
> 
> ```python
>     imgs_mask_test_true = np.load('imgsliv_test.npy')  #groundtruth masks
>     return imgst, imgs_mask_test_true
> ```
> 
> in the notebook replace
> 
> ```python
> imgs_test, imgs_id_test = load_test_data()
> ```
> 
> by
> 
> ```python
> imgs_test = load_test_data()[0]
> ```

Thank you! Its working now. :)
